Añadimos el model de usuario
z1digitalstudio/halfcms pull request #1
Opened 2019-02-25 06:41 UTC by martabecerra

Creamos el modelo de usuario.

2019-02-25 08:23 UTC, emiliosanchez commented on .gitignore
> +#por culpa de la instalacion de uikit ¿habría que haberlo hecho fuera?
En realidad no necesitabas instalar uikit ya que lo vas a cargar desde su CDN. De todas formas está bien tener node_modules en el .gitignore

2019-02-25 08:27 UTC, emiliosanchez requested changes

2019-02-25 08:27 UTC, emiliosanchez commented on .gitignore
> +yarn.lock
Ignorar *.json es un poco arriesgado. Para empezar package.json tiene los requisitos node de tu proyecto y no lo queremos ignorar sino conservarlo para que todos puedan instalar esos requisitos. Por otra parte los .lock tampoco deben ser ignorados, ni el yarn.lock ni el package.lock ya que son utiles para congelar las versiones de los paquetes y que no haya diferencias entre un despliegue y otro.

2019-02-25 08:27 UTC, emiliosanchez commented on user/models.py
> +    username = models.CharField(max_length=100, blank=True, null=True)
Casi, no queremos que username sera optativo, queremos que no exista en el modelo.

2019-02-25 08:42 UTC, martabecerra commented on user/models.py
> +    username = models.CharField(max_length=100, blank=True, null=True)
username=None

2019-02-25 08:48 UTC, martabecerra commented
Modificado

2019-02-25 09:55 UTC, emiliosanchez approved these changes

2019-02-25 09:57 UTC, emiliosanchez requested changes

2019-02-25 09:57 UTC, emiliosanchez commented on user/models.py
> +    username = None
Creo que con este cambio vas a necesitar una migracion nueva para eliminar el campo del modelo. Cada vez que hagas cambios en los modelos necesitaras ejecutar el `makemigrations`.

Por otra parte sin ese campo va a fallar el UserAdmin que tendrás que modificar también.

2019-02-27 06:41 UTC, martabecerra commented on user/models.py
> +    username = None
Echa la migración y eliminado el modelo de UserAdmin ya que como dices necesitaba el username.

He subido la card de autenticación.. pero como está este PR abierto... ya me dices cómo lo gestiono.

2019-02-27 11:34 UTC, emiliosanchez requested changes

2019-02-27 11:34 UTC, emiliosanchez commented on base/views.py
> +                                        )
En SignUpForm ya tiénes la lógica para guardar un usuario, así que podrías cambiar todo lo que has montado alrededor de `userObj` por un `user = form.save()`, despues haces el authenticate y el login.

2019-02-27 11:34 UTC, emiliosanchez commented on user/models.py
> +    def create_user(self, email, password=None, **kwargs):
Casí, fijate que ahora tu método create_user acepta un numero indeterminado de argumentos con nombre a través de `**kwargs`. Sin embargo en el código de este método no lo estás usando en ningun sitio. Por lo que cualquier cosa que entre por ahí se ignorará.

Sin probarlo imagino que cualquier usuario que crees con el código actual no tendra ni first_name ni last_name. Lo que puedes hacer es pasar todos los parametros que capturas en `**kwargs` a la creación de usuario en `user = self.model(email=self.normalize_email(email),)` simplemente añadelos: `user=self.model(email=self.normalize_email(email), **kwargs)`

2019-02-27 11:40 UTC, emiliosanchez commented on user/models.py
> +    def create_user(self, email, password=None, **kwargs):
Ok, veo que esto está arreglado en un commit posterior :+1:

2019-02-27 12:41 UTC, merged